[package]
name = "supplier"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "Provider API polyfill. WIP"
authors = ["Conrad Ludgate <conradludgate@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
